data_loading:
  train_or_test: test  # can take values 'train' or 'test'
  train_path: data/squad1.1/train-v1.1.json
  test_path: data/squad1.1/dev-v1.1.json
  drop_impossible: true  # only useful for squad2.0 : whether to drop the impossible questions or not

model :
  name: bm25

model_parameters :
  bm25 : 
    dataset_percentage: 0.01  # for the test set, 0.01=106 samples, takes a few seconds to compute
  bert:
    pretrained_model_name: bert-base-uncased
    context_embeddings_path: results/bert_context_embeddings_{train_or_test}.pt     # {train_or_test} will be replaced by train or test
    question_embeddings_path: results/bert_question_embeddings_{train_or_test}.pt   # depending on the value of train_or_test
    batch_size: 2
    dataset_percentage: 0.01
    compute_more_question_embeddings: true # if set to false, the program will compute new question embeddings only if none are pre-saved

metrics : 
  list_top_k: [1, 5, 10]  # during evaluation, will print the number of questions for which the true context is in the top k predicted contexts

seed : 42