data_loading:
  train_path: data/squad2.0/train-v2.0.json
  test_path: data/squad2.0/dev-v2.0.json
  drop_impossible: true

model :
  name: bert

model_parameters :
  bm25 : 
    dataset_percentage: 0.01  # 0.01=868 samples if drop_impossible=True, takes ~5 minutes to compute
    top_n : 10
  bert:
    pretrained_model_name: bert-base-uncased
    context_embeddings_path: results/bert_context_embeddings.pt
    prediction_df_path: results/bert_predictions.csv
    batch_size: 2
    dataset_percentage: 0.0001
    new_samples_only: true
    always_compute_questions_embeddings: true # if set to false, the program will compute question embeddings only if none are pre-saved

results :
  parent_folder_path: results/
  result_folder_name : datetime # if datetime then will be the current date and time by convention
  exist_ok : false

seed : 42