data_loading:
  train_path: data/squad2.0/train-v2.0.json
  test_path: data/squad2.0/dev-v2.0.json
  drop_impossible: true

model :
  name: bm25

model_parameters :
  bm25 : 
    dataset_percentage: 0.01  # 0.01=868 samples if drop_impossible=True, takes ~5 minutes to compute
    top_n : 3

seed : 42