data_loading:
  train_path: data/squad2.0/train-v2.0.json
  test_path: data/squad2.0/dev-v2.0.json
  drop_impossible: true

model :
  name: bm25

model_parameters :
  bm25 : 
    dataset_percentage: 0.01  # 0.01=868 samples if drop_impossible=True, takes ~5 minutes to compute
    top_n : 10

results :
  parent_folder_path: results/
  result_folder_name : datetime # if datetime then will be the current date and time by convention
  exist_ok : false

seed : 42